import { motion } from "framer-motion";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/sections/Footer";
import { GlassCard } from "@/components/ui/GlassCard";
import { Search, Filter, Clock, Users, Star, BookOpen, Sparkles, ChevronRight, Award } from "lucide-react";
import { useState } from "react";

const categories = ["All", "Computer Science", "System Design", "Career", "Data Science", "Product"];

const allCourses = [
  {
    title: "Data Structures & Algorithms Masterclass",
    category: "Computer Science",
    description: "Master essential data structures and algorithmic patterns for technical interviews.",
    duration: "12 hours",
    students: "15.2K",
    rating: 4.9,
    modules: 24,
    gradient: "from-primary to-secondary",
    isNew: true,
  },
  {
    title: "System Design for Senior Engineers",
    category: "System Design",
    description: "Learn to design scalable distributed systems from scratch.",
    duration: "8 hours",
    students: "8.7K",
    rating: 4.8,
    modules: 16,
    gradient: "from-secondary to-accent",
    isNew: false,
  },
  {
    title: "Behavioral Interview Excellence",
    category: "Career",
    description: "Master the STAR method and ace any behavioral question.",
    duration: "4 hours",
    students: "22.1K",
    rating: 4.9,
    modules: 10,
    gradient: "from-accent to-primary",
    isNew: false,
  },
  {
    title: "Machine Learning Fundamentals",
    category: "Data Science",
    description: "Build a strong foundation in ML concepts and algorithms.",
    duration: "16 hours",
    students: "11.3K",
    rating: 4.7,
    modules: 32,
    gradient: "from-primary via-secondary to-accent",
    isNew: true,
  },
  {
    title: "Product Sense & Strategy",
    category: "Product",
    description: "Develop product thinking skills for PM interviews.",
    duration: "6 hours",
    students: "6.8K",
    rating: 4.8,
    modules: 14,
    gradient: "from-secondary to-primary",
    isNew: false,
  },
  {
    title: "Graph Algorithms Deep Dive",
    category: "Computer Science",
    description: "Advanced graph algorithms for competitive programming and interviews.",
    duration: "10 hours",
    students: "4.2K",
    rating: 4.9,
    modules: 20,
    gradient: "from-accent via-primary to-secondary",
    isNew: true,
  },
];

const Courses = () => {
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");

  const filteredCourses = allCourses.filter((course) => {
    const matchesCategory = selectedCategory === "All" || course.category === selectedCategory;
    const matchesSearch = course.title.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-24 pb-12">
        <div className="container mx-auto px-6">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-8"
          >
            <h1 className="font-display text-4xl sm:text-5xl font-bold mb-4">
              Explore <span className="gradient-text">AI Courses</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl">
              Personalized learning paths generated by AI, tailored to your goals and skill level.
            </p>
          </motion.div>

          {/* AI Course Generator CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="mb-10"
          >
            <GlassCard hover={false} gradient className="flex flex-col sm:flex-row items-center gap-6 py-6">
              <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary via-secondary to-accent flex items-center justify-center shrink-0">
                <Sparkles className="w-8 h-8 text-primary-foreground" />
              </div>
              <div className="flex-1 text-center sm:text-left">
                <h2 className="font-display text-xl font-semibold mb-1">Generate Custom Course</h2>
                <p className="text-muted-foreground">
                  Tell AI what you want to learn, and we'll create a personalized course just for you.
                </p>
              </div>
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-primary to-secondary text-primary-foreground font-semibold flex items-center gap-2 shrink-0"
              >
                Create Course
                <ChevronRight className="w-5 h-5" />
              </motion.button>
            </GlassCard>
          </motion.div>

          {/* Search and Filters */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-8"
          >
            <div className="flex flex-col sm:flex-row gap-4 mb-6">
              <div className="relative flex-1">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="Search courses..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-12 pr-4 py-3 rounded-xl glass border border-border focus:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all"
                />
              </div>
              <button className="px-6 py-3 rounded-xl glass border border-border hover:border-primary/50 flex items-center gap-2 transition-colors">
                <Filter className="w-5 h-5" />
                Filters
              </button>
            </div>

            <div className="flex flex-wrap gap-2">
              {categories.map((category) => (
                <motion.button
                  key={category}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => setSelectedCategory(category)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                    selectedCategory === category
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {category}
                </motion.button>
              ))}
            </div>
          </motion.div>

          {/* Course Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredCourses.map((course, index) => (
              <motion.div
                key={course.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 + index * 0.05 }}
              >
                <GlassCard className="h-full flex flex-col">
                  {/* Course header */}
                  <div className={`h-32 -mx-6 -mt-6 mb-4 bg-gradient-to-br ${course.gradient} rounded-t-xl flex items-center justify-center relative overflow-hidden`}>
                    <BookOpen className="w-12 h-12 text-primary-foreground/80" />
                    {course.isNew && (
                      <div className="absolute top-3 right-3 px-2 py-1 rounded-md bg-background/90 text-xs font-semibold text-primary">
                        NEW
                      </div>
                    )}
                  </div>

                  <div className="flex-1 flex flex-col">
                    <div className="text-xs text-primary font-medium uppercase tracking-wide mb-2">
                      {course.category}
                    </div>
                    <h3 className="font-display text-lg font-semibold mb-2">
                      {course.title}
                    </h3>
                    <p className="text-sm text-muted-foreground mb-4 flex-1">
                      {course.description}
                    </p>

                    <div className="flex items-center justify-between text-sm text-muted-foreground mb-4">
                      <div className="flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        {course.duration}
                      </div>
                      <div className="flex items-center gap-1">
                        <Users className="w-4 h-4" />
                        {course.students}
                      </div>
                      <div className="flex items-center gap-1">
                        <Star className="w-4 h-4 text-yellow-500" />
                        {course.rating}
                      </div>
                    </div>

                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted-foreground">{course.modules} modules</span>
                      <motion.button
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        className="px-4 py-2 rounded-lg bg-primary/10 border border-primary/30 text-primary font-medium text-sm hover:bg-primary/20 transition-colors"
                      >
                        Enroll Free
                      </motion.button>
                    </div>
                  </div>
                </GlassCard>
              </motion.div>
            ))}
          </div>

          {/* Certificate Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="mt-16"
          >
            <GlassCard hover={false} className="flex flex-col md:flex-row items-center gap-8 py-8">
              <div className="w-24 h-24 rounded-2xl bg-gradient-to-br from-yellow-500 to-orange-500 flex items-center justify-center shrink-0">
                <Award className="w-12 h-12 text-primary-foreground" />
              </div>
              <div className="flex-1 text-center md:text-left">
                <h2 className="font-display text-2xl font-bold mb-2">Earn Verified Certificates</h2>
                <p className="text-muted-foreground">
                  Complete courses to earn blockchain-verified certificates with QR codes. 
                  Share your achievements with employers and showcase your skills.
                </p>
              </div>
              <motion.button
                whileHover={{ scale: 1.02 }}
                className="px-6 py-3 rounded-xl glass border border-border hover:border-primary/50 font-medium transition-colors shrink-0"
              >
                Learn More
              </motion.button>
            </GlassCard>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Courses;
